name: Sync README to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up huggingface-cli
        run: pip install huggingface_hub

      - name: Log in to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Push README to Hugging Face
        run: git push hf main
