name: Sync README to Hugging Face

on:
  push:
    branches: [ main ]   # change to master if your branch is master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Show repo files
        run: ls -la

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Upload README.md to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'EOF'
          from huggingface_hub import HfApi
          import os, glob

          print("Files in root:", os.listdir("."))
          candidates = glob.glob("README.md") + glob.glob("readme.md") + glob.glob("Readme.md")
          if not candidates:
              raise FileNotFoundError("No README.md found in repo root!")
          readme_path = candidates[0]
          print(f"Found README at: {readme_path}")

          api = HfApi()
          api.upload_file(
              path_or_fileobj=readme_path,
              path_in_repo="README.md",
              repo_id="keshavbhandari/Structure-Derivation",
              repo_type="model",
              token=os.environ["HF_TOKEN"]
          )
          EOF
